### ISSUE TITLE
[Feature] Improve schema error reporting and language translation

### ISSUE THREAD

**Issue by fmigneault** [crim-ca/weaver#112]
# Context

Since `colander` is used to validate input schemas of requests body and generated responses, it is possible to better handle the returned errors as translated text. Given that `Accept-Language` header is now also supported (#74, #82), we should report invalid inputs messages accordingly in the REST API.

More precisely, when a `colander.Invalid` (exception) schema is generated, the responses contain messages as `TranslationString` ([pyramid.i18n](https://docs.pylonsproject.org/projects/pyramid/en/latest/api/i18n.html)), which can be used to return locale-aware descriptions.

# TODO

- [ ] remove all try/except everywhere around the wps-rest portion of the code for `colander.Invalid` and move them to the `tween` as a single HTTPBadRequest catch. Using a global catch of `colander.Invalid`, we can run the translation string operations with the full error stack since they are accumulated from the first raised to the top.
- [ ] Use `asdict` or similar variants for error reporting. For the moment, items like `oneOf` aggregates error strings which makes it extremely hard to read. All there errors are dumped in the response `description` which is "cleaned", but all the special characters and string concatenation generates a lot of garbage. The description should be replaced by a generic (summary) string, and another field would have the full detail as dict/list.
- [ ] add `weaver` domain with corresponding message strings for the app. `colander` messages are pre-packaged with it. Not only errors should be translated, but as must items as possible such as successful deployment or job status.

reference code (minimal - not complete)
```
def translator(key="<msgid>", domain="colander"):
    return <translation>

try: 
    # ...
except: 
    invalid = colander.Invalid()
    invalid.add(<more-error>)
    invalid.add(<more-error>)
    raise invalid 

# in tween
# returns a dict of all steps that caused an error with mapping
# also .messages() available for a list of strings
invalid.asdict(translate=translator)
# ... 
```

**Comment by fmigneault** [comment]
```
#: Mapping of language codes send by browsers to supported dialects.
BROWSER_LANGUAGES = {
    'en': 'en_CA',
    'en-ca': 'en_CA',
    'en-us': 'en_CA',
    'en-gb': 'en_CA',
    'fr': 'fr_CA',
    'fr-ca': 'fr_CA',
    'fr-fr': 'fr_CA'
}

def locale_negotiator(request):
    """Locale negotiator for pyramid views.

This version differs from Pyramid's :py:func:`default_locale_negotiator
<pyramid.i18n.default_locale_negotiator>` in that it has a fallback to the
preferred languages from browser.
"""
    locale = default_locale_negotiator(request)  # default 'en'
    if locale is None and request.accept_language:
        locale = request.accept_language.best_match(BROWSER_LANGUAGES.keys()).lower()
        # default to en_GB as it does not have silly units etc...
        locale = BROWSER_LANGUAGES.get(locale, 'en_GB')
        request._LOCALE_ = locale

    return locale
```

**Comment by fmigneault** [comment]
```
from pyramid.i18n import TranslationString, make_localizer

colander_locale = <path-to-colander-pkg>/locale
ts = TranslationString('Required', domain='colander')
L = make_localizer('fr', [colander_locale])
L.translate(ts, domain='colander')    # will return 'Requis'
```
