### ISSUE TITLE
[Bug] Missing process I/O field details

### ISSUE THREAD

**Issue by fmigneault** [crim-ca/weaver#211]
**Missing elements to fix**

- When using `/processes/...` 
  - [x] Many of the input/output fields are not returned (`dataType`, `anyValue`, `allowedValues`, etc.) (relates to #41)
  - [x] Other fields dependent on the literal data type I/O are also missing (`literalDataDomain`, types of range, etc.)
  - [x] Complex data type must be updated by modifying `mimeType` to `mediaType`. 
    Old `mimeType` format should be allowed for deployment backward-compatibility, but descriptions will be reported with the standard `mediaType` 
    (https://github.com/opengeospatial/ogcapi-processes/commit/748bba6e4d4883f116e290141b4cda26aab3bda8)

- When using `/providers/...` 
  - [x] fields available as passed literally during `DescribeProcess`, but still returns partial sub-fields any extra details such as ranges are not parsed.
  - [x] `GetCabilities` should not have the empty lists of `inputs` and `outputs` (#203) 

- [ ] Bbox data type still missing completely (#51)

References: 
https://github.com/opengeospatial/ogcapi-processes/blob/master/core/openapi/schemas
https://github.com/opengeospatial/ogcapi-processes/blob/master/core/openapi/schemas/inputDescription.yaml
https://github.com/opengeospatial/ogcapi-processes/blob/master/core/openapi/schemas/outputDescription.yaml

**Comment by fmigneault** [comment]
only `mediaType` portion is fixed by #285
