### ISSUE TITLE
[Feature] Support I/O `schema` field definition

### ISSUE THREAD

**Issue by fmigneault** [crim-ca/weaver#245]
PR https://github.com/opengeospatial/ogcapi-processes/pull/172 introduces the requirements for `schema` provided in every input and output definition to represent the expected format of `value` when submitting inputs and retrieving output results. 

This field can be easily added for basic types that are defined by Literal I/O and Complex I/O since the type of `value` is always known. The multiplicity via `minOccurs` and `maxOccurs` can also be used to formulate the corresponding JSON schema fields and whether the expected `schema` of `value` is a direct value or an array of them. The `AllowedValues` and `SupportedValues` definitions can be used to define the `enum` values of a `string`, if needed, similarly to how it is already resolved to form the CWL payload. Ranges, min/max int/float values require slightly more logic, but should also be solvable with corresponding WPS/CWL parameters.

When supporting this feature, the corresponding "Requirements Class" ~with "JSON Schema Level"~ should be added to the conformance list accordingly to how much we support ~(currently only Level 0)~. 
https://github.com/pvretano/ogcapi-processes/blob/issue-170/core/clause_7b_jsonschema.adoc

**update**: Levels were removed, feature superseded by PR https://github.com/opengeospatial/ogcapi-processes/pull/181 

# todo

- [x] Update conformance list with JSON schema support
- [x] Update I/O JSON generation in process description outputs to provide the computed `schema` definition
- [x] For every **Deploy** I/O, the `schema` should be optional to remain backward compatible. If provided, it should be used as-is in the resulting process I/O (after validation that it is a proper OpenAPI schema definition).
- [x] For every **Described* process I/O, `schema` should be **required** (as per OGC-API). Missing (omitted) explicit  specification from deployment, for builtin processes, or already existing processes, `schema` should be generated transparently from other I/O metadata to fulfill the requirement.
- [x] ~Update `FormatSchema` to employ `FileURL` instead of `ReferenceURL` since other variants are not publicly accessible nor resolvable by schema validators~ ignored 
  https://github.com/crim-ca/weaver/blob/3ab577bcf43994f6a0ac47d8f9312f70914999e2/weaver/wps_restapi/swagger_definitions.py#L575-L581
- [x] ~Remove `schema = FormatSchema(missing=drop)` definitions in all `[Deploy]Format[MimeType|MediaType]` definitions since the schema will be one level higher, in the I/O definition itself rather than under `formats` field.~
  Left for backward compatibility if used by some input that provided more details about the expected schema for a given media-type input/output, but unused. 
- [x] Tests (items defined in [opengeospatial/ogcapi-processes/core/abstract_tests/ogc-process-description](https://github.com/opengeospatial/ogcapi-processes/tree/855ccbd3409fe011e6b6fadba3307b75924f5106/core/abstract_tests/ogc-process-description))
