### ISSUE TITLE
[Feature] Support Prefer header and improve sync/async execution

### ISSUE THREAD

**Issue by fmigneault** [crim-ca/weaver#247]
# Context

Support the different method of controlling, specifying or proposing execution mode (sync/async). 

Following PRs proposes the modification of `mode` in the payload to use `Prefer` header [[RFC-7240 #2](https://datatracker.ietf.org/doc/html/rfc7240#section-2)].
https://github.com/opengeospatial/ogcapi-processes/pull/174 
https://github.com/opengeospatial/ogcapi-processes/pull/194

# Todo

- [x] For backward compatibility reasons, `mode` should still be supported. 
- [x] The `Prefer` header would become another way to specify it, taking precedence on `mode` as it would be the official method.
  - `Prefer: respond-async` should be mapped to `mode: async-execute`. 
  - `Prefer: wait=<x>` should be mapped to `mode: sync-execute` if supported, and timeout if wait time is reached.
  - `Prefer: wait` timeout should resume the request as if `Prefer: respond-async` was indicated.
- [x] Both `mode` and `Prefer` should be optional, with `mode: auto` resolving to `async-execute` in the case of Weaver. 
- [x] ~When `sync-execute` is not supported (or vice versa with `async`) by a process, HTTP 412 should be immediately returned with a clear message of the reason if `mode` was employed.~ Since `mode` is not a header, 412 cannot be employed as precondition header failed.
- [x] When using `Prefer` instead, when the execution mode is not supported, processing should transparently ignore the unsupported mode and switch to the supported one (`Prefer` requirement is that it MUST ignore errors [[RFC-7240 #2](https://datatracker.ietf.org/doc/html/rfc7240#section-2)]). 
- [x] When `Prefer` was provided, the `Preference-Applied` header [[RFC-7240 #3](https://datatracker.ietf.org/doc/html/rfc7240#section-3)] should be provided in the response to indicate the auto-resolution. 
- [x] To support above points, processes should define 'supported' execution modes in their `jobControlOptions`. 
  This will also depend on whether Weaver correctly supports `sync` or not. Also, some type of processes like a CWL Workflow *could* be enforced `async`-only since they are usually always longer to complete to be reasonably `sync` in a timely manner.
- [x] ~For backward compatibility reasons, an empty `jobControlOptions` should be considered as supporting both `sync-execute` and `async-execute`.~ Applied for `builtin` processes since their execution is relatively small. Other processes will keep returning only `async-execute` if not explicitly provided. They should be updated (re-deployed) if they should support both modes.
- [x] Update documentation about available modes:  https://github.com/crim-ca/weaver/blob/c7990fc6688724a6d8396bc139e9d7490880413d/docs/source/processes.rst?plain=1#L381-L385

Requirements: 
- [x] auto-resolution of execution mode based on `Prefer=respond-async` (and bw-compat `mode=auto|async-execute`)
  https://github.com/opengeospatial/ogcapi-processes/blob/master/core/requirements/core/REQ_job-creation-auto-execution-mode.adoc
- [x] default-resolution of execution mode when NO `Prefer` or `mode` was provided
  https://github.com/opengeospatial/ogcapi-processes/blob/master/core/requirements/core/REQ_job-creation-default-execution-mode.adoc
- [x] more details on combinations of request params/headers vs expected responses
    https://github.com/pvretano/ogcapi-processes/blob/issue-217/core/sections/clause_7_core.adoc#process-outputs

[412 Precondition Failed](https://www.restapitutorial.com/httpstatuscodes.html)
> The precondition given in one or more of the request-header fields evaluated to false when it was tested on the server. This response code allows the client to place preconditions on the current resource meta information (header field data) and thus prevent the requested method from being applied to a resource other than the one intended.

# Extra

Improve support of `sync` 

Considering that `sync` could effectively "lock" workers if too many blocking requests are made simultaneously, some logic will need to be added to avoid the issue. Minimally 1 worker should remain as not assignable to `sync` jobs such that the API can still respond to new requests (including non-job related ones). Again  HTTP 412 should be returned in that case to indicate that the server cannot respond to the demand, but should probably consider adding another "error code" string to differentiate between categorically refused mode vs not applicable temporarily because server is busy. ~Otherwise 503 Service Unavailable could also be considered.~

# Tests

Compliance with the various items, tests and definitions in: 
https://github.com/opengeospatial/ogcapi-processes/pull/174/files
