### ISSUE TITLE
Properly support `type` as the method to specific file references inputs

### ISSUE THREAD

**Issue by fmigneault** [crim-ca/weaver#401]
## Description

When providing an execution input as `file` type (via `href` field), the `type` (rather than `mediaType` or `mimeType` or `format` with this information nested under it) is the official OGC-API way to specific the applicable media-type: 
- https://github.com/opengeospatial/ogcapi-processes/blob/master/core/openapi/schemas/inlineOrRefData.yaml  (`link.yaml` being the "file reference")
- https://github.com/opengeospatial/ogcapi-processes/blob/master/core/openapi/schemas/link.yaml#L10-L12

## TODO

- [x] For backward compatibility, previous methods should still be supported.
- [x] File reference should be detected solely using `href` and not depend on `format(s)` anymore.
- [x] Detection of `type` should be supported as equivalent to 
  ~`format: <mediaType>` or~ `format: { mediaType: <mediaType>, ... }`

## References

- Relates to #245
