### ISSUE TITLE
Support I/O literal with unit of measure

### ISSUE THREAD

**Issue by fmigneault** [crim-ca/weaver#430]
## Description

Literals can be provided either directly, or nested under `value` field during execution.
This nested `value` allows adding other informational fields next to it. 

A common use of extra fields is to provide a unit of measure (`uom`) defining the "scale" of the specified value, as well as a `reference` describing the unit itself. This case is sufficiently common to be present in both recent OGC-API examples and PyWPS literals implementations parameters (see references).

# ToDo

- [x] Detect the `uom` specified for a literal during execution to include it (ie: add it to the `LiteralInput`).
- [x] Consider parsing of OpenAPI `object` as literal in this specific case. 
    With #245, `object` are either converted to bounding box or complex input/output. This is a new variant that would have to be considered for process description and deployment.
- [x] Process "known" `uom` (see URN shortcuts) when applicable.
- [x] Given that `uom` is the only "known" field, the value itself could be define is many ways (`value`, `measure`, `measurement`, etc.). Since it is required, consider using the `required` field within the `schema` to identify where the value is. Otherwise, fallback to those "common" names (?) or raise directly at deployment time that the `required` field should be specified.
  - [x] During process deployment
  - [x] During process execution
- [x] Determine given a provided unit of measure during execution, how should this be passed to CWL?
    Since CWL is simply a script command, it only passes the value. Converting/scaling the value is not necessarily trivial for more complex or non-metric units.

## References

- MeasureInput `schema` example:  https://github.com/opengeospatial/ogcapi-processes/blob/d5257909ae9dbb8cf9958ef251e44cb3a903d691/core/examples/json/ProcessDescription.json#L27-L49
- https://github.com/geopython/pywps/blob/511a2b208c8951f99b0d16bf0c2ced6006b85868/pywps/inout/inputs.py#L296-L303
- https://github.com/geopython/pywps/blob/f7f00ecc35fb1750f5fca740bfd9dfe8abdade42/pywps/inout/outputs.py#L284-L290
- `UOM` class: https://github.com/geopython/pywps/blob/f7f00ecc35fb1750f5fca740bfd9dfe8abdade42/pywps/inout/basic.py#L63-L81
- OGC UoM URN shortcuts: https://github.com/geopython/pywps/blob/f7f00ecc35fb1750f5fca740bfd9dfe8abdade42/pywps/__init__.py#L80-L89

**Comment by fmigneault** [comment]
UoM support blockd by https://github.com/geopython/pywps/issues/685 for non-OGC units.
