### ISSUE TITLE
Conformance route

### ISSUE THREAD

**Issue by fmigneault** [crim-ca/weaver#53]
Conformance route should be implemented to link standards that the application conforms to and/or supports.

`GET /conformance`

see example: 
https://github.com/opengeospatial/oapi_common/blob/master/standard/examples/conformance_response_JSON_1.adoc

Also update docs reference links to return (old pdf ref seem to be missing) :
- [x] https://github.com/opengeospatial/wps-rest-binding
- [ ] https://opengeospatial.github.io/architecture-dwg/api-processes/index.html

Following is done for now: 
https://github.com/crim-ca/weaver/blob/0b67d701bb75bcbbeebe559b1aa9ab7e7c363c38/weaver/wps_restapi/api.py#L54-L153

Following still must be added :
- CWL specifications:  
  - [ ] https://www.commonwl.org/#Specification (in both conformsTo and frontpage links)
  - [ ] https://www.commonwl.org/v1.0/CommandLineTool.html (only conformsTo)
  - [ ] https://www.commonwl.org/v1.0/Workflow.html (only conformsTo)
  - [ ] https://www.commonwl.org/v1.1/CommandLineTool.html (only conformsTo)
  - [ ] https://www.commonwl.org/v1.1/Workflow.html (only conformsTo)
- WPS-REST 
  - [ ] http://www.opengis.net/spec/ogcapi-processes/ (under frontpage links)
  - [ ] http://www.opengis.net/spec/ogcapi-processes/1.0/req/core (under conformsTo)
  - [ ] http://www.opengis.net/spec/ogcapi-processes/1.0/conf/core (under conformsTo)
  - [ ] other items under above `ogcapi-processes` namespace?
    (identified from: https://github.com/opengeospatial/wps-rest-binding/search?q=rc_core&unscoped_q=rc_core) 
- see also: https://github.com/opengeospatial/wps-rest-binding/issues/71

Slightly more official/recent conformance definitions: 
https://htmlpreview.github.io/?https://github.com/opengeospatial/ogcapi-processes/blob/master/docs/18-062.html#_conformance

- [ ] Core: http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/core
- [ ] Processes: http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/ogc-process-description
- [ ] JSON: http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/json
- [ ] HTML: http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/html  (implementation needed #210)
- [ ] OAS3: http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/oas30
- [ ] Job list: http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/job-list
- [ ] Callback: http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/callback (implementation needed #230)
- [ ] Dismiss: http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/dismiss (implementation needed #228)
